#!/bin/bash

failed=0

cd "$(cd "$(dirname "$0")"; pwd -P)/.."

python py-chrome-bookmarks.py test/Bookmarks test/bookmarks_actual_output.html
cmp -s test/bookmarks_expected_output.html test/bookmarks_actual_output.html

if [[ $? -ne 0 ]]; then
	echo "The bookmarks script produced unexpected output:"
	diff test/bookmarks_expected_output.html test/bookmarks_actual_output.html
	failed=1
fi

python py-chrome-history.py test/History test/history_actual_output.html
cmp -s test/history_expected_output.html test/history_actual_output.html

if [[ $? -ne 0 ]]; then
	echo "The history script produced unexpected output:"
	diff test/history_expected_output.html test/history_actual_output.html
	failed=1
fi

if [[ "$failed" == "1" ]]; then
	exit 1
fi
